### ISSUE TITLE
Facets disappear on Search Pages when selected

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/ajax_facets#11]
If I enable Ajax Facets on a Search_Pages (search_api_page) then click on any facet, they all disappear (I have 3 facets).  If I use standard facets everything works.  Unfortunately I really need ranges of some kind for prices.  Facets Dynamic Ranges has it's problems as well.

This is what I am seeing in the log:
_Notice: Undefined variable: view in ajax_facets_refresh_facets_content() (line 159 of /home/xxx/public_html/modules/ajax_facets/ajax_facets.pages.inc)._

With the location of: https://yyy.xxx.com/ajax/ajax_facets/refresh

These same facets with Ajax enabled work fine on my views based catalog.  I can drill down deep into each facet.  I have product category, brand and price with 1700+ products.

**Comment by argiepiano** [comment]
After a quick look at the function that's giving the notice, it seems to me that this only works with Views-based searches. It will probably need some adaptations to work with Search API Pages.

**Comment by samgreco** [comment]
Thanks.  I will have to see if there is a way to use views to accomplish this.

**Comment by argiepiano** [comment]
I've found these [tutorials](https://www.drupal.org/docs/7/modules/search-api/getting-started/search-forms-and-results-pages/search-api-views) on using Search API views very helpful.  Also this [video](https://www.youtube.com/watch?v=hcAM0HrEk4c) may be helpful.

**Comment by samgreco** [comment]
Thanks a bunch for the info.  Built a search view and all works well.
